name: binaryen-hs
version: 0.0.1
category: Compiler
stability: alpha
maintainer: Shao Cheng <cheng.shao@tweag.io>
copyright: (c) 2020 Tweag I/O
license: BSD3
github: tweag/binaryen

extra-source-files:
  - binaryen/**/**
  - CHANGELOG.md
  - LICENSE

custom-setup:
  dependencies:
    - base
    - Cabal
    - directory
    - filepath

extra-libraries:
  - stdc++
  - binaryen

ghc-options: -Wall

dependencies:
  - base

library:
  generated-exposed-modules: Paths_binaryen_hs
  source-dirs: src
